name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/la_inocente_1.jpeg
  - assets/images/qlona.png
  - assets/images/fondo.png
  - assets/images/exitos_reggaeton.jpeg
  - assets/images/luna.png
  - assets/images/exclusivo.png
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/favorito_3_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/favorito_x2.svg
  - assets/vectors/favorito_1_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/favorito_2_x2.svg
  - assets/images/la_inocente.png
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/images/fondo.png
  - assets/images/logo.png
  - assets/images/fondo.png
  - assets/images/logo.png
  - assets/images/fondo.png
  - assets/images/logo.png
  - assets/images/logo.png
  - assets/images/fondo.png
  - assets/images/logo.png
  - assets/images/pa_planchar.jpeg
  - assets/images/salsa_clasica.jpeg
  - assets/images/reggaeton_viejito.jpeg
  - assets/images/exitos_reggaeton.jpeg
  - assets/images/fondo.png
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_9_x2.svg


